name: Dev Branch Tests

on:
  push:
    branches: [rinsedev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run placeholder test
      run: echo "Tests will run here soon 🚀"

  #     - name: Run tests
  # run: npm ci && npm run test
